### ISSUE TITLE
Count Sort Algorithm in Java

### ISSUE THREAD

**Issue by vishal-kumar-saw** [ShivamYadav-Coding/hacktoberfest-2021#100]
Hello @ShivamYadav-Coding sir, can I work on this issue of writing code for the count sort algorithm in java? If yes then kindly assign me this project. Thank you.

**Comment by tokyo-arch** [comment]
hello sir can you please assign this issue to me.

**Comment by tokyo-arch** [comment]
> @tokyo-arch Since java language has already been assigned to vishal, You have to choose a different language.



> @tokyo-arch please specify your language.

cpp

**Comment by ShivamYadav-Coding** [comment]
@tokyo-arch Sorry but this count sort algorithm had already been implement in cpp previously.
