### ISSUE TITLE
Coin Change Problem - C language

### ISSUE THREAD

**Issue by vishal-kumar-saw** [ShivamYadav-Coding/hacktoberfest-2021#101]
Given a value N, if we want to make change for N cents, and we have infinite supply of each of S = { S1, S2, .. , Sm} valued coins, how many ways can we make the change? The order of coins doesn’t matter.
For example, for N = 4 and S = {1,2,3}, there are four solutions: {1,1,1,1},{1,1,2},{2,2},{1,3}. So output should be 4. For N = 10 and S = {2, 5, 3, 6}, there are five solutions: {2,2,2,2,2}, {2,2,3,3}, {2,2,6}, {2,3,5} and {5,5}. So the output should be 5.

Hello @ShivamYadav-Coding sir, kindly allow me to work on this issue in C language, and assign me this. Also please add the tags for hacktoberfest. Thank you.

**Comment by DurveshKumarPal** [comment]
HEY, can you assign me to under hactoberfest
