### ISSUE TITLE
About adding few sorting programs.

### ISSUE THREAD

**Issue by whyanujjwhy** [ShivamYadav-Coding/hacktoberfest-2021#22]
Hi, I would like to add some sorting algorithms to the repo! Can you assign it to me?

**Comment by whyanujjwhy** [comment]
1. heapSort in cpp
2. quickSort in py

**Comment by Razor-123** [comment]
I would like to work on this.
I am 3 star at codechef (with user_id:razor_321) and also familiar with sorting algorithms
I can add:
1. Merge sort in cpp
2. Bubble sort in cpp
can you assign it to me?

**Comment by ShivamYadav-Coding** [comment]
@Razor-123 please make a new issue.

**Comment by shreya3071** [comment]
Hi, I want to add some sorting algorithms:
1. Quick sort in cpp
2. Insertion sort in cpp
