### ISSUE TITLE
Sorting an Array through SelectionSort

### ISSUE THREAD

**Issue by Rohat-Iftikhar** [ShivamYadav-Coding/hacktoberfest-2021#27]
Hello! I would love to contribute a java program to sort an array through SelectionSort! Can you please assign it to me?

**Comment by ShivamYadav-Coding** [comment]
Go ahead and make a pull request ;)

**Comment by gauri20pa** [comment]
Can I contribute to sorting array by Radix Sort? Can you please assign me for it?

**Comment by harsh6975** [comment]
I can sort array using any sorting algorithm in c++/Java.
Selection sort uses selectivity (can choose min/max element and fix it), although it is best for array Quicksort.
 I'll explain the code as well as the intuition behind the code.
Would you mind assigning me too?
Thanks

**Comment by ShivamYadav-Coding** [comment]
@gauri20pa  and @harsh6975 Yes you can cotribute but make sure that it is not already present in repository or any other contributor is not working on it.
