### ISSUE TITLE
Sorting in c language

### ISSUE THREAD

**Issue by Razor-123** [ShivamYadav-Coding/hacktoberfest-2021#40]
I would like to add following sorting algorithm in **C** language :
1. selection sort
2. bubble sort
3. insertion sort
Please assign this to me so I start working on it.

**Comment by mrvishalsharma** [comment]
can i work on this issue?

**Comment by ShivamYadav-Coding** [comment]
@mrvishalsharma you cannot work on c and c++ as sorting algoirthms in these languages has already been implemented by other cotributers.

**Comment by ShivamYadav-Coding** [comment]
@Razor-123 you could go ahead in c

**Comment by Razor-123** [comment]
@ShivamYadav-Coding sir i did it. please review the pr.

**Comment by mrvishalsharma** [comment]
> 
> 
> @mrvishalsharma you cannot work on c and c++ as sorting algoirthms in these languages has already been implemented by other cotributers.

ok sir but if you need in any other language rather than c and c++ like in java,python,c# , javascript then i would love to contribute

**Comment by ShivamYadav-Coding** [comment]
@mrvishalsharma You can cotribute these sorting algorithms in kotline, javascript, csharp.

**Comment by ShivamYadav-Coding** [comment]
@mrvishalsharma the go ahead and make a pull request for any language.

**Comment by mrvishalsharma** [comment]
> 
> 
> @mrvishalsharma the go ahead and make a pull request for any language.

sure sure
