### ISSUE TITLE
Sorting an array using insertion sort.

### ISSUE THREAD

**Issue by Yasir36** [ShivamYadav-Coding/hacktoberfest-2021#43]

**Comment by Yasir36** [comment]
insertion sort in java

**Comment by SaranshGupta6** [comment]
i like to contribute on this issue please assign it to me

**Comment by ShivamYadav-Coding** [comment]
@SaranshGupta6 Cotribute some other program. Because of first come first serve policy i am going to assign this issue to Yasir36.

**Comment by Yasir36** [comment]
> @SaranshGupta6 Cotribute some other program. Because of first come first serve policy i am going to assign this issue to Yasir36.

Thank you, submitted a PR.
