### ISSUE TITLE
Repository is open for contribution now :partying_face:

### ISSUE THREAD

**Issue by ShivamYadav-Coding** [ShivamYadav-Coding/hacktoberfest-2021#7]
### This repository is now open for contribution.
**Guidelines -**
- Everyone has to open an issue regarding what program or project they want to add inside repository before making pull request for it.
- If the issue is for a new program then they need to comment under that issue about which language they want to use for that program( other person could also comment). Then that issue will be assigned to that person for that language. Any person could contribute upto two program in different language for a particular issue.
- Please add folder of your projects inside project folder and programs inside its appropriate folder according to language used.
- Example for a issue [click here](https://github.com/ShivamYadav-Coding/hacktoberfest-2021/issues/6)

**Comment by Prateek-kannojia** [comment]
hi @ShivamYadav-Coding can I add android project created in java?? if yes please assign me this issue with hacktober fest tag.
