### ISSUE TITLE
want to add an android project.

### ISSUE THREAD

**Issue by Prateek-kannojia** [ShivamYadav-Coding/hacktoberfest-2021#77]
i want to add an android project that i have created in java .

**Comment by ShivamYadav-Coding** [comment]
Please explain your project in brief.

**Comment by Prateek-kannojia** [comment]
my project based is convertor that converts length, volume, area and temperature offline, and converts currency online based on daily values of currency... can you please add hacktober fest tag also.

**Comment by ShivamYadav-Coding** [comment]
You could work on it.
