### ISSUE TITLE
Performing a Merge sort algorithm using JavaScript

### ISSUE THREAD

**Issue by Sudeep8708** [ShivamYadav-Coding/hacktoberfest-2021#84]
Hey, I would like to add the code of performing Merge Sort Algorithm using JavaScript. Since, the sorting algorithms present in the JavaScript repo (currently), are not that efficient in terms of Time Complexity. I would like to add the code, so can you please assign it to me. Also, it will be helpful if you're adding the Hactoberfest Tag for this issue. Thanks !

**Comment by ShivamYadav-Coding** [comment]
Okay.
